import type { NextPage } from 'next'
import Head from 'next/head'
import SideMenu from './sidemenu'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Doni Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Dashboard /> */}
      <SideMenu />
    </div>
  )
}

export default Home
